spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kinkim?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: im@kin.kim[yT0o/tBDsLDMKDJkWsmSMLT1D1F6VdjJQ2piv1kJVmsT66+q3xZlaIrfe8PaU1OFhgdfywgTilVb2q2J/mWH2yPIezWRJR5WhUNp+thJJyH1UwT7GL+aGy8peUU5dv6ORWxyLC/xJK4kFuS3Exum5B2Yf1owj1oRHeVyzknK47FynIY75g6UCpMnInIxlJwZIGFmOwn1B7FKwqewhtC1+Xx4QELFFr5ACKD4k2q3cfjl8xkdXBkfsaiWwhikLJjWGX5Hfy0ry0NagAAFis9BA9LQobSemfyl6iiyBuPpHQ2MXQDaE7NzVF9O77tf/0GVJhKg8dT3VaDNYOy9S9AcaQ==]
    password: im@kin.kim[NACfREF4LFIQFDM7MXotJilYF/b2gX+CkgvnPbRxRtqCiQ1UcZsqW2idQ2+fnxpnF6tGZlR+XYqvpMvRk7tms9B+Mv/M582EUk+gIdugS46sjzL/1q8RZ9fuVpNe6deWsggwqZwVXj1E7z/hKk4B0VAmY+32gIoRZrDxu/JSu52saCMjx1TIAvYPb4Ms8pO3xUo6M56ew9TAO0SKIHDR/4KpvrzrtsYKLUyyy31a0+WRNq/4n4CmqQXiDwuspMb5ap8V1g27nvhuPBytIhVOP7RdeV/kcSzMury9lKMbMrcBdGetC93s1mie7stn2uGx7ApMRRJo1ejjXK8ZbkQsrQ==]
  data:
    redis:
      host: localhost
      password: im@kin.kim[NACfREF4LFIQFDM7MXotJilYF/b2gX+CkgvnPbRxRtqCiQ1UcZsqW2idQ2+fnxpnF6tGZlR+XYqvpMvRk7tms9B+Mv/M582EUk+gIdugS46sjzL/1q8RZ9fuVpNe6deWsggwqZwVXj1E7z/hKk4B0VAmY+32gIoRZrDxu/JSu52saCMjx1TIAvYPb4Ms8pO3xUo6M56ew9TAO0SKIHDR/4KpvrzrtsYKLUyyy31a0+WRNq/4n4CmqQXiDwuspMb5ap8V1g27nvhuPBytIhVOP7RdeV/kcSzMury9lKMbMrcBdGetC93s1mie7stn2uGx7ApMRRJo1ejjXK8ZbkQsrQ==]
      port: 6379
      database: 0
jasypt:
  encryptor:
    #    algorithm: PBEWITHHMACSHA512ANDAES_256
    #    password: a2lua2lt
    property:
      prefix: "im@kin.kim["
      suffix: "]"
    private-key-format: pem
    public-key-format: pem
    #    private-key-location: classpath:id_rsa_pkcs8
    #    public-key-location: classpath:id_rsa_pkcs8.pem
    private-key-location: file:/home/devops/.ssh/id_rsa_pkcs8
    public-key-location: file:/home/devops/.ssh/id_rsa_pkcs8.pem
kim:
  kin:
    logpath: ${user.home}/data/logs


